Adding a new question in faq page
microsoft/edx-theme pull request #69
Opened 2017-04-12 21:16 UTC by ms-manikarthik

Adding a new question in faq page

2017-04-12 21:20 UTC, satyarapelly approved these changes

2017-04-12 21:28 UTC, kabirkhan commented
This doesn't include all the updates from Rhonda.

2017-04-12 21:29 UTC, kabirkhan commented
We need to add the question about searching from Infopedia

2017-04-12 21:29 UTC, btelnes approved these changes
Verified that requested changes in Rhonda's 4/12 email are present.

2017-04-12 21:29 UTC, sdolenc approved these changes

2017-04-12 21:39 UTC, eltoncarr commented
There are a number of diffs between what is expected and what is currently on the page.

2017-04-12 21:39 UTC, eltoncarr-ms requested changes
There are a number of diffs between what is expected and what is currently on the page.

Answer doesn't match requirement:
- [ ] How will I be notified of courses that are applicable to my role?
- [ ] Will I be able to discover open edX courses on Infopedia?
- [ ] Will my manager see the courses I’ve taken in InfoPedia? (possibly bad encoding)

Is the email representing the final version of the faq? If so, some existing questions need to be removed as well:
- [ ] Q. Iâ€™d like to try the Open edX experience, but no courses are available to me right now.
- [ ] Q.What do I do if I cannot access a course and I get an error saying my email address belongs to another account, and to try again with a different address?

2017-04-12 22:42 UTC, sdolenc requested changes
i'd like to test this in fullstack before approving. can you share the url of a fullstack deployment that has these changes? if not, swing by and we'll apply these changes to one of my fullstacks and we'll share that url to the team : )

2017-04-12 22:42 UTC, sdolenc commented on courses/lms/templates/static_templates/faq.html
>          <img src="/static/courses/images/download_video.png" alt="download_video_img" height="400">
can you share the url of a fullstack deployment that has these changes? if not, swing by and we'll apply these changes to one of my fullstacks and we'll share that url to the team : )

2017-04-12 22:43 UTC, eltoncarr commented
You can also pull the raw content, let the browser render it and do the comparisons. Right now, it seems the network is flaky…

From: Stephen Dolenc [mailto:notifications@github.com]
Sent: Wednesday, April 12, 2017 3:42 PM
To: Microsoft/edx-theme <edx-theme@noreply.github.com>
Cc: Elton Carr <eltonc@microsoft.com>; Comment <comment@noreply.github.com>
Subject: Re: [Microsoft/edx-theme] Adding a new question in faq page (#69)


@sdolenc requested changes on this pull request.

i'd like to test this in fullstack before approving. can you share the url of a fullstack deployment that has these changes? if not, swing by and we'll apply these changes to one of my fullstacks and we'll share that url to the team : )

________________________________

In courses/lms/templates/static_templates/faq.html<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoft%2Fedx-theme%2Fpull%2F69%23discussion_r111276781&data=02%7C01%7Celtonc%40microsoft.com%7C34ec84eb8ce644a181bc08d481f5276d%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636276337307953721&sdata=gBjtmgH5cYgtBWC%2B1fgHgeVuZwgdBHK%2BE8JflGq7ZZs%3D&reserved=0>:

>      <b>Q. I’d like to try the Open edX experience, but no courses are available to me right now.</b>

         <p>The best way to get a sense of the user experience is by taking the edX Demo course. You can also find over 100 courses delivered by Microsoft that are open to the public on <a href="https://www.edx.org/school/microsoft">https://www.edx.org/school/microsoft.</a></p><br<https://www.edx.org/school/microsoft.%3c/a%3e%3c/p%3e%3cbr>>

-    <b>Q. What do I do if I am having trouble viewing a video?</b><br>

-        <p>Please click on the download video button located below the video player. See screenshot.</p><br>

+    <b>Q.What do I do if I cannot access a course and I get an error saying my email address belongs to another account, and to try again with a different address?</b><br>

+           <p> A. This is because you already created an account on the Azure Skills Initiative site using your @microsoft.com email address. You should log into the Azure site on <a href="https://openedx.microsoft.com"> https://openedx.microsoft.com</a<https://openedx.microsoft.com%3c/a>> and change your email address under Account Settings. We recommend that you update the email address with a personal email address. After this, please try to launch your course again from MyLearning or the link you were provided.</p><br>

+       <b>Q. What do I do if I am having trouble viewing a video?</b><br>

+        <p>The video player will auto-select the best video quality option for your bandwidth. You can try a lower quality option, or you can download the video if that option is available. See screenshot.

+

+</p><br>

         <img src="/static/courses/images/download_video.png" alt="download_video_img" height="400">

can you share the url of a fullstack deployment that has these changes? if not, swing by and we'll apply these changes to one of my fullstacks and we'll share that url to the team : )

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoft%2Fedx-theme%2Fpull%2F69%23pullrequestreview-32511364&data=02%7C01%7Celtonc%40microsoft.com%7C34ec84eb8ce644a181bc08d481f5276d%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636276337307953721&sdata=idLMOGGBpq7VDYbrBCxhba6%2FLafKV%2BOEJuvuqQBRoe8%3D&reserved=0>, or mute the thread<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAVmU23SFLgWYTo7woVVWQPYU42lU2Yg_ks5rvVNAgaJpZM4M7-yU&data=02%7C01%7Celtonc%40microsoft.com%7C34ec84eb8ce644a181bc08d481f5276d%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636276337307953721&sdata=R7cjRFWVMycC7Y1a%2FK1bK5%2BnRnrUYjPfUn7q9FOfQPg%3D&reserved=0>.

2017-04-12 23:25 UTC, sdolenc approved these changes

2017-04-13 16:31 UTC, eltoncarr-ms approved these changes
Seems key concerns were met.

2017-04-13 16:33 UTC, merged