Explore Courses in Course View
microsoft/edx-theme pull request #90
Opened 2017-06-23 16:53 UTC by ElakkiyaMohanRajan

#### What's this PR do? Any additional context?
Allow the user to view all the courses even though he didn't sign in or Register
#### Where should the reviewer start?
Click on any course in the main page and now the use can see the Explore Course link to view all other courses
#### How can this be manually tested? (brief repro steps)
Before: There is no provision to able to view all the other course
After  : Now the user can able to see the Explore Course link
#### What are the relevant TFS items? (list id numbers)
User Story : 91635
#### Definition of done:
- [ ] Title of the pull request is clear and informative
- [ ] Add pull request hyperlink to relevant TFS items
- [x] For large or complex change: schedule an in-person review session

[//]: # ( todo: Is there appropriate test coverage? )
[//]: # ( todo: Does this PR require a new Selenium test? )
[//]: # ( todo: Is there appropriate logging/monitoring included? )

#### Reminders BEFORE merging
1. Get at least two approvals
1. If you're merging into the development branch then "flatten" or "squash" commits
1. If merging from development into master then don't "flatten" or "squash" commits

#### Reminders AFTER merging
1. Delete the remote branch
1. Resolve relevant TFS items
1. (reverse merge) If you merged into master then check to see if there are any changes in master that can be merged down to the development branch (like hotfixes, etc)

[//]: # ( todo: If you merged into development branch then verify change in our "rolling deployment" environment. Then notify stakeholders interested in or involved with the change )

[//]: # ( fyi: This content was heavily inspired by )
[//]: # ( 1 Our team's policies and processes )
[//]: # ( 3 https://github.com/sprintly/sprint.ly-culture/blob/master/pr-template.md )
[//]: # ( 4 The book "The Checklist Manifesto: How to Get Things Right" by Atul Gawande )
[//]: # ( 5 https://github.com/Azure/azure-event-hubs/blob/master/.github/PULL_REQUEST_TEMPLATE.md )

2017-06-23 16:53 UTC, msftclas commented
@ElakkiyaMohanRajan,
Thanks for your contribution as a Microsoft full-time employee or intern. You do not need to sign a CLA.
_Thanks,
Microsoft Pull Request Bot_

2017-06-23 18:15 UTC, ms-hukoyun approved these changes

2017-06-23 18:19 UTC, btelnes approved these changes

2017-06-23 18:21 UTC, manikarthikk approved these changes

2017-06-23 18:22 UTC, partpa approved these changes

2017-06-23 22:22 UTC, kevsers requested changes
I want to little bit discuss about this solution, I am curious if that should be achieved through configuration change only. As we add the same code piece within the if condition above.
Have you checked what our value in production for 'ENABLE_COURSE_DISCOVERY' is?

2017-07-01 00:00 UTC, kevsers approved these changes

2017-07-01 00:03 UTC, merged